### ISSUE TITLE
Error when saving shippingrules

### ISSUE THREAD

**Issue by CMeldgaard** [KuriousAgency/commerce-currency-prices#19]
**Error**
After update to latest Craft Commerce / Craft, the shipping rules breaks when saving. When pushing save, i get the following error: Trying to access array offset on value of type null

As far as i can see, the error occurs because these fields:
![image](https://user-images.githubusercontent.com/14794642/120278630-cd0d4480-c2b5-11eb-8831-e0507429331f.png)

Gets replaces with just the maximumfield
![image](https://user-images.githubusercontent.com/14794642/120278670-db5b6080-c2b5-11eb-9bf2-ef4e2a0d4f87.png)

Therefor when looping thru the fields in the ShippingService, the minTotalCP field is missing in the request.

**Stacktrace:**
```
yii\base\ErrorException: Trying to access array offset on value of type null
#13 /opt/bitnami/apache/htdocs/releases/2021-05-31T0853/vendor/kuriousagency/commerce-currency-prices/src/services/ShippingService.php(124): handleError
#12 /opt/bitnami/apache/htdocs/releases/2021-05-31T0853/vendor/craftcms/cms/src/web/ErrorHandler.php(76): handleError
#11 /opt/bitnami/apache/htdocs/releases/2021-05-31T0853/vendor/kuriousagency/commerce-currency-prices/src/services/ShippingService.php(124): getPrices
#10 /opt/bitnami/apache/htdocs/releases/2021-05-31T0853/vendor/kuriousagency/commerce-currency-prices/src/controllers/ShippingController.php(161): actionSave
#9 /opt/bitnami/apache/htdocs/releases/2021-05-31T0853/vendor/kuriousagency/commerce-currency-prices/src/controllers/ShippingController.php(0): call_user_func_array
#8 /opt/bitnami/apache/htdocs/releases/2021-05-31T0853/vendor/yiisoft/yii2/base/InlineAction.php(57): runWithParams
#7 /opt/bitnami/apache/htdocs/releases/2021-05-31T0853/vendor/yiisoft/yii2/base/Controller.php(181): runAction
#6 /opt/bitnami/apache/htdocs/releases/2021-05-31T0853/vendor/craftcms/cms/src/web/Controller.php(190): runAction
#5 /opt/bitnami/apache/htdocs/releases/2021-05-31T0853/vendor/yiisoft/yii2/base/Module.php(534): runAction
#4 /opt/bitnami/apache/htdocs/releases/2021-05-31T0853/vendor/craftcms/cms/src/web/Application.php(278): runAction
#3 /opt/bitnami/apache/htdocs/releases/2021-05-31T0853/vendor/craftcms/cms/src/web/Application.php(581): _processActionRequest
#2 /opt/bitnami/apache/htdocs/releases/2021-05-31T0853/vendor/craftcms/cms/src/web/Application.php(257): handleRequest
#1 /opt/bitnami/apache/htdocs/releases/2021-05-31T0853/vendor/yiisoft/yii2/base/Application.php(392): run
#0 index.php(29): null
```

**Versions:**
Craft: 3.6.15
Commerce: 3.3.3
Commerce Currency Prices: 2.7.1

**Comment by CMeldgaard** [comment]
Is there any status on this error?
